language: cpp
compiler: gcc

install:
  # fparser
  - cd ..
  - git clone https://github.com/richelbilderbeek/fparser.git
  #- git clone https://github.com/thliebig/fparser.git
  - cd fparser
  - qmake
  - make
  - cd ..
  - cd travis_qmake_gcc_cpp98_fparser 

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp98_fparser
